language: node_js
sudo: false

# -----------------------------------------------------------------------------
# Regular builds
# -----------------------------------------------------------------------------

# Node.js version and necessary services
node_js:
  - 10
  - node # check for latest release

os:
  - osx

services:
  - docker

# Limit clone depth to 5, to speed up build
git:
  depth: 5

# Cache dependencies
cache:
  yarn: true
  directories:
    - node_modules

# Install yarn as Travis doesn't support it out of the box
before_install:
  - npm install -g yarn@v1.10.1

# Install dependencies
install:
  - yarn install

# Perform tests
script:
  - yarn lint && yarn test
